import { vi } from 'vitest';

vi.mock('../../src/config/env', () => ({
  env: {
    port: 3001,
    jwtSecret: 'test-secret',
    accessTokenTtlSeconds: 900,
    refreshTokenTtlSeconds: 2592000,
    refreshTokenReuseGraceSeconds: 20,
    rateLimitRefreshMax: 60,
    databaseUrl: 'postgresql://user:pass@localhost:5432/db',
    profileServiceUrl: 'http://localhost:3002',
    kafkaBrokers: 'localhost:9092',
    redisUrl: 'redis://localhost:6379',
    corsOrigin: false,
    fetchTimeoutMs: 5000,
    rateLimitMax: 60,
    rateLimitRegisterMax: 5,
    rateLimitVerifyEmailMax: 10,
    rateLimitLoginMax: 10,
    emailVerificationTtlSeconds: 600,
    maxCodeAttempts: 5,
    verificationCodeSecret: 'test-code-secret',
    authFailWindowSeconds: 900,
    authFailNotifyThreshold: 5,
    rateLimitPasswordResetMax: 5,
    rateLimitAccountDeleteMax: 5,
    passwordResetTtlSeconds: 600,
    adminApiKey: 'test-admin-key',
  },
}));
